<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpVectors" Version="1.8.6" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="LogoApp.svg" />
    <Resource Include="LogoApp.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>